qt: fix missing Cocoa include
Applies patch from:
https://code.qt.io/cgit/qt/qtbase.git/commit/src/plugins/platforms/cocoa?id=dece6f5840463ae2ddf927d65eb1b3680e34a547

Fixes the same issue:
https://github.com/microsoft/vcpkg/issues/21055

./qiosurfacegraphicsbuffer.h:54:32: error: use of undeclared identifier 'CGColorSpaceRef'